version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: movie-watchlist-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - movie-watchlist-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-watchlist-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongodb
    networks:
      - movie-watchlist-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-watchlist-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - movie-watchlist-network

volumes:
  mongodb_data:

networks:
  movie-watchlist-network:
    driver: bridge
