apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bojanaandonova/movie-watchlist-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VITE_API_URL
        - name: BACKEND_SERVICE_NAME
          value: "backend-service"
        - name: BACKEND_SERVICE_PORT
          value: "5000"
