apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  init-mongo.js: |
    print("Starting database initialization...");
    
    db = db.getSiblingDB('movie_watchlist');
    
    var appUsername = process.env.MONGO_APP_USERNAME;
    var appPassword = process.env.MONGO_APP_PASSWORD;
    
    db.createUser({
      user: appUsername,
      pwd: appPassword,
      roles: [{ role: 'readWrite', db: 'movie_watchlist' }]
    });
    
    print("Application user '" + appUsername + "' created successfully");
    
    // Create indexes for better performance
    db.movies.createIndex({ "status": 1 });
    db.movies.createIndex({ "genre": 1 });
    db.movies.createIndex({ "created_at": 1 });
    db.movies.createIndex({ "title": 1 });
    
    print("Database initialization completed!");
