apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  username: YWRtaW4=            # admin
  password: cGFzc3dvcmQxMjM=    # password123
  app-username: dXNlcm5hbWU=    # username
  app-password: cGFzczEyMw==    # pass123
