apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      app.kubernetes.io/name: movie-watchlist
      app.kubernetes.io/version: "1.0.0"
  template:
    metadata:
      labels:
        app: mongodb
        app.kubernetes.io/name: movie-watchlist
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          value: movie_watchlist
        - name: MONGO_APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: app-username
        - name: MONGO_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: app-password
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongodb-init-script
        configMap:
          name: mongodb-config
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
