apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: movie-watchlist

resources:
  - namespace.yaml
  - configmap.yaml
  - mongodb/secret.yaml
  - mongodb/configmap.yaml
  - mongodb/statefulset.yaml
  - mongodb/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/name: movie-watchlist
  app.kubernetes.io/version: "1.0.0"