name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker images to Docker Hub"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add EC2 instance to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd '/home/ubuntu/movie-watchlist-app' 
            
            git pull origin main
            
            docker-compose pull
            
            docker-compose down
            
            docker-compose up -d
            
            docker image prune -f
            
            docker-compose ps

      - name: Health Check
        run: |
          echo "Waiting for services to start..."
          sleep 30
          
          # Check if backend is responding
          if curl -f http://${{ secrets.EC2_HOST }}:5000/health; then
            echo "Backend is healthy"
          else
            echo "Backend health check failed"
            exit 1
          fi
          
          # Check if frontend is responding
          if curl -f http://${{ secrets.EC2_HOST }}:80; then
            echo "Frontend is healthy"
          else
            echo "Frontend health check failed"
            exit 1
          fi
