name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - "main"  
  pull_request:
    branches:
      - "main" 

jobs:
  # Lint Code Base
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Docker Build and Push
  docker:
    runs-on: ubuntu-latest
    needs: run-lint  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images using docker-compose
        run: |
          docker-compose -f docker-compose.yml build  # Build all services defined in docker-compose.yml
          docker-compose -f docker-compose.yml push   # Push images to DockerHub
